version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - python -m pip install -r docs/requirements.txt
    - python -m sphinx -b html docs/source $READTHEDOCS_OUTPUT/html -c docs/

python:
  install:
    - requirements: docs/requirements.txt