device: cpu
is_train: True
i2i_checkpoint_path: '/Users/hoangthuyduongvu/Desktop/BiOSGen/checkpoints'

train: 
  batch_size: 10
  num_epochs: 100
  save_epoch_freq: 10
  model: 
    generator: 
      netG: 'resnet_9blocks'
      ngf: 64
      normG: 'instance'

    discriminator: 
      netD: 'n_layers'
      init_type: 'normal'
      init_gain: 0.02
      ndf: 64
      n_layers_D: 3
      normD: 'instance' 

    projector:
      netF: 'mlp_sample'
      netF_nc: 256
      init_type: 'normal'
      init_gain: 0.02

    init_type: 'normal'
    init_gain: 0.02
    no_antialias: False
    no_antialias_up: False
  
  data: 
    input_nc: 3
    output_nc: 3
    patch_size: 64
    max_src_samples: 1
    downsample: 1
  
  
  params: 
    image_model_name: 'vgg16'
    loss:
      gan_loss: 
        gan_mode: 'lsgan'
        nce_idt: True
        lambda_NCE: 1.0
        nce_layers: '0,4,8,12,16'
        nce_num_patches: 256  
        flip_equivariance: False
        nce_includes_all_negatives_from_minibatch: False
        nce_T: 0.07

      sc_loss: 
        lambda_con: 1.0
        lambda_sty: 1.0

    optimizer:
      lr: 
        lr_G: 0.0002
        lr_D: 0.0002
        lr_I: 0.0002
        lr_policy: 'plateau'

      params:
        beta1: 0.5
        beta2: 0.999
        weight_decay: 0.0

    is_image_match: True
    patch_batch_size: 256
    patch_norm: True   # Fix later if necessary
    patch_clip: True   # Fix later if necessary

    save: 
      continue_train: False

test: 
  model_epoch: 25


Image:
  default_size: 128
  default_channels: 3

  tissue_mask_params: 
    kernel_size: 20
    sigma: 20
    downsample: 8
    background_gray_threshold: 220

  patch_extraction_params:
    patch_size: 128
    patch_tissue_threshold: 0.7
    is_visualize: False